filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
- input_type: log
  paths:
    - /data/*.json
  document_type: "pcap_file" # use to define custom mapping
  json.keys_under_root: true

output.logstash:
  hosts: ["logstash:5044"]